### ISSUE TITLE
Helping hand needed

### ISSUE THREAD

**Issue by ddeimeke** [opensourcegreasemonkey/hugo-embed-pdf-shortcode-demo#2]
Thank you very much for your documentation of embed-pdf.

I am an absolute beginner with Hugo and it does not seem to work for me.

Can you please give me a helping hand?

https://changelog.deimeke.ruhr/2019/08/11/workshop-20190811/
https://changelog.deimeke.ruhr/workshop-regex.pdf

```
+++
title = "Workshop: Einführung in Reguläre Ausdrücke"
description = ""
tags = [
    "workshop",
]
    date = 2019-08-11T12:10:00Z
author = "Dirk Deimeke"
+++

## Einführung in Reguläre Ausdrücke

<p> Dieser Workshop ist eine Einführung in das Suchen und Ersetzen mit Regulären Ausdrücken. </p>

{{ < embed-pdf url="/workshop-regex.pdf" > }}

https://programm.froscon.de/2019/events/2465.html
```

Thanks in advance!

**Comment by anvithks** [comment]
Hey there @ddeimeke .
This is the source code for the demo site .
The source for the shortcode is located [here](https://github.com/anvithks/hugo-embed-pdf-shortcode)
There are some updates there which haven't been added to the demo site yet. 
Is your website hosted on GitHub or is the source code visible anywhere?

**Comment by ddeimeke** [comment]
Hi @anvithks 

Many thanks for your support.

I deployed the shortcode as "requested".

Unfortunately it still does not work.

Do I have to run hugo with any special settings?

Cheers

Dirk

**Comment by anvithks** [comment]
> Hi @anvithks 
> 
> Many thanks for your support.
> 
> I deployed the shortcode as "requested".
> 
> Unfortunately it still does not work.
> 
> Do I have to run hugo with any special settings?
> 
> Cheers
> 
> Dirk

Hello Dirk,

No special settings needed.
Is your source code available on Github or are you building and deploying the built code on a web server?

One thing i see is the pdf file should be placed alongside your content

**Comment by ddeimeke** [comment]
Hi Anvith,

I sent you the link to my source code by e-mail.

Cheers

Dirk

**Comment by anvithks** [comment]
@ddeimeke I have gone through the repository you shared and set it up locally.
There are a few steps that you have missed from the setup.
Ensure that the shortcode has been setup properly. You can find the setup instructions [here](https://github.com/anvithks/hugo-embed-pdf-shortcode#setup)

This shortcode is not shipped with Hugo and you have to configure your setup to use the shortcodes.
You can see how a custom shortcode is created [here](https://gohugo.io/templates/shortcode-templates/)

This repository holds the code for the demo but it is not updated with the latest code, yet.

I will do that shortly but you can clone the [anvithks/hugo-embed-pdf-shortcode](https://github.com/anvithks/hugo-embed-pdf-shortcode) repository and use the latest code from there.

Here is a screenshot with the working PDF.

![image](https://user-images.githubusercontent.com/19162717/131681611-e7f8c4f2-587a-46dc-a7e1-e15bb21e3e5c.png)

**Comment by ddeimeke** [comment]
Sorry @anvithks 

I already did it, but I did not commit it.

Can you please check once more?

Most probably I am doing something wrong.

So many thanks for your support.

**Comment by anvithks** [comment]
@ddeimeke I just sent you an email with detailed instructions and also working source code that I setup locally.

Try it out and let me know if it works.

**Comment by anvithks** [comment]
@ddeimeke I just checked your code repository.
Just make these changes.

1. Place the pdf file alongside your .md source file. In your case the `post` directory.
2. The shortcode is incorrect. The path of the file should be `./workshop-regex.pdf`. Notice the `./`. 
3.  There is an extra space after `{{` and before `<` and same with the closing tags. 
4. This is the correct format `{{< embed-pdf url="./workshop-regex.pdf" >}}`

Let me know how it goes.

**Comment by ddeimeke** [comment]
It works now, many thanks.

My directory was called layout, lacking the "s" at the end and the embed-pdf.html was different.

```
diff --git a/layouts/shortcodes/embed-pdf.html b/layouts/shortcodes/embed-pdf.html
index e977f03..cf72178 100644
--- a/layouts/shortcodes/embed-pdf.html
+++ b/layouts/shortcodes/embed-pdf.html
@@ -1,4 +1,5 @@
-<script type="text/javascript" src= '{{"/" | relURL}}/js/pdf-js/build/pdf.js'></script>
+<!-- If using the baseURL then use this src= '{{"/" | relURL}}js/pdf-js/build/pdf.js'  -->
+<script type="text/javascript"src= '{{"/" | relURL}}js/pdf-js/build/pdf.js'></script>
 <style>
 #the-canvas {
   border: 1px solid black;
@@ -58,7 +59,9 @@
 window.onload = function() {
 // If absolute URL from the remote server is provided, configure the CORS
 // header on that server.
-var url = "{{.Site.BaseURL}}" + '{{ .Get "url" }}';
+// var url = '{{ .Get "url" }}';
+// If using the baseURL then use the following and comment line 62
+ var url = "{{.Site.BaseURL}}" + '{{ .Get "url" }}';
 
 var hidePaginator = "{{ .Get "hidePaginator" }}" === "true";
 var hideLoader = "{{ .Get "hideLoader" }}" === "true";
@@ -68,7 +71,10 @@ var selectedPageNum = parseInt("{{ .Get "renderPageNum" }}") || 1;
 var pdfjsLib = window['pdfjs-dist/build/pdf'];
 
 // The workerSrc property shall be specified.
-pdfjsLib.GlobalWorkerOptions.workerSrc = "{{.Site.BaseURL}}" + '/js/pdf-js/build/pdf.worker.js';
+// pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.8.335/build/pdf.worker.min.js';
+
+// The workerSrc property shall be specified. Use the following line to specify the baseURL and comment line 74.
+pdfjsLib.GlobalWorkerOptions.workerSrc = "{{.Site.BaseURL}}" + 'js/pdf-js/build/pdf.worker.js';
 
 // Change the Scale value for lower or higher resolution.
 var pdfDoc = null,
@@ -190,12 +196,9 @@ pdfjsLib.getDocument(url).promise.then(function(pdfDoc_) {
   pdfDoc = pdfDoc_;
   var numPages = pdfDoc.numPages;
   document.getElementById('page_count').textContent = numPages;
-  
-  // If the user passed in a number that is out of range, render the last page.
   if(pageNum > numPages) {
     pageNum = numPages
   }
-
   // Initial/first page rendering
   renderPage(pageNum);
 });
```

**Comment by anvithks** [comment]
@ddeimeke Awesome! 
You can use the latest embed-pdf.html from the  shortcode repository.
